### ISSUE TITLE
请问能否共享失信被执行人的数据

### ISSUE THREAD

**Issue by bruce4research** [JunjieLeiCoe/WebScraper_Research2020S#1]
您好，感谢您关于失信被执行人的代码。由于学位论文需要，请问您是否可以将该数据分享给我呢？

期待您的回复。

**Comment by bruce4research** [comment]
另外汇报我发现的两个问题：

- 抓取到1000多条的时候，还是出现了“页码累加，但是信息未变的情况”。

- ID_Num似乎有误。如图所示，前几行人员信息与ID_Num对不上。

![图片2](https://user-images.githubusercontent.com/52608168/99869792-c025df00-2c08-11eb-9d2a-574dba388e5d.png)

**Comment by JunjieLeiCoe** [comment]
Sorry, the data set is too hard to deliver. (> 7G, 9 million observations)
We will release the data after the research is finished, sometime in the future.
